on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - run: flutter build apk --release --split-per-abi
      # ----------Below is for IOS, IOS ko lagi yo bata chalena kei issue aayo, andriod lai matra chalxa aile lai--------
      # - run: |
      #     flutter build ios --no-codesign
      #     cd build/ios/iphoneos
      #     mkdir Payload 
      #     cd Payload
      #     ln -s ../Runner.app
      #     cd ..
      #     zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          # --------------Both IOS and andriod ko lagi yo use garne-----------------------------------
          # artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.MERO_MOVIE_TOKEN }}
# push to master, main, develop
# pull request on main master
